# Generated by Django 2.2.6 on 2019-10-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yandex_token',
            field=models.TextField(default=''),
        ),
    ]
