# Generated by Django 2.2.6 on 2019-11-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdomain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetext',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometext', to='subdomain.Domain', verbose_name='Для поддомена'),
        ),
    ]
