# Generated by Django 2.2.6 on 2019-11-30 15:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdomain', '0002_auto_20191114_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='googleTAG',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения google'),
        ),
        migrations.AddField(
            model_name='domain',
            name='yandexTAG',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения Яндекс'),
        ),
        migrations.AlterField(
            model_name='homepagetext',
            name='fullText',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст для главной страницы. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AlterField(
            model_name='servicepagetext',
            name='fullText',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст для страницы услуги, Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
    ]
