# Generated by Django 2.2.6 on 2019-10-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writtenBy',
            field=models.CharField(default='', max_length=75, verbose_name='От кого отзыв'),
        ),
    ]
