# Generated by Django 2.2.6 on 2019-12-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20191130_1850'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ManyToManyField(blank=True, to='service.ServiceName', verbose_name='Отзыв к услугам'),
        ),
    ]
