# Generated by Django 2.2.7 on 2020-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название '),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание '),
        ),
    ]
