# Generated by Django 2.2.7 on 2020-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200213_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog_img/', verbose_name='Изображение превью (555 x 390)'),
        ),
    ]
