# Generated by Django 2.2.6 on 2019-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Тег DESCRIPTION для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='keywords',
            field=models.TextField(max_length=255, null=True, verbose_name='Тег KEYWORDS для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='tagH1',
            field=models.CharField(max_length=255, null=True, verbose_name='Тег Н1 для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%. Например: Заказать в городе %TOWN% курсовую работу '),
        ),
        migrations.AddField(
            model_name='servicename',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Тег TITLE для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
    ]
