# Generated by Django 2.2.6 on 2019-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Предмет')),
            ],
        ),
        migrations.AlterField(
            model_name='servicename',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Вид работы'),
        ),
    ]
