# Generated by Django 2.2.6 on 2019-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191114_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Срок выполнения, например 14 дней'),
        ),
    ]
