# Generated by Django 2.2.6 on 2019-11-25 17:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20191125_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seotag',
            name='homeDefaultText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Заполните это поле', null=True, verbose_name='Текст для главной страницы, если не указан иной'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='defaultText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Заполните это поле', null=True, verbose_name='Текст для вставки на страницу услуги, если не указан иной'),
        ),
    ]
