# Generated by Django 2.2.6 on 2020-02-16 12:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20191130_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='compareTitle',
            field=models.CharField(blank=True, default='Доверьте написание дипломной работы нам', max_length=255, verbose_name='Заголовок для раздела сравнения'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='faqTitle',
            field=models.CharField(blank=True, default='Ответы на вопросы', max_length=255, verbose_name='Заголовок для раздела FAQ'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='featuresTitle',
            field=models.CharField(blank=True, default='Нам доверяют потому что:', max_length=255, verbose_name='Заголовок для раздела приемущества'),
        ),
        migrations.CreateModel(
            name='SubServiceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Подвид работы')),
                ('name_lower', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('time', models.CharField(max_length=20, verbose_name='Срок выполнения, например 14 дней')),
                ('faqTitle', models.CharField(blank=True, default='Ответы на вопросы', max_length=255, verbose_name='Заголовок для раздела FAQ')),
                ('featuresTitle', models.CharField(blank=True, default='Нам доверяют потому что:', max_length=255, verbose_name='Заголовок для раздела приемущества')),
                ('compareTitle', models.CharField(blank=True, default='Доверьте написание дипломной работы нам', max_length=255, verbose_name='Заголовок для раздела сравнения')),
                ('tagH1', models.CharField(max_length=255, null=True, verbose_name='Тег Н1 для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%. Например: Заказать в городе %TOWN% курсовую работу ')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Тег TITLE для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Тег DESCRIPTION для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%')),
                ('keywords', models.TextField(max_length=255, null=True, verbose_name='Тег KEYWORDS для страницы с услугой. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%')),
                ('defaultText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Заполните это поле', null=True, verbose_name='Текст для вставки на страницу услуги, если не указан иной')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceName', verbose_name='Основной вид работы')),
            ],
            options={
                'verbose_name': 'Подвид работы',
                'verbose_name_plural': 'Подвиды работ',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Описание приемущества ')),
                ('icon', models.ImageField(null=True, upload_to='services_img/', verbose_name='Иконка (100х100)')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceName', verbose_name='Приемущество для основного вида работы')),
                ('subService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.SubServiceName', verbose_name='Приемущество для подвида работы')),
            ],
            options={
                'verbose_name': 'Приемущество услуги',
                'verbose_name_plural': 'Приемущества услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, null=True, verbose_name='Ответ')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceName', verbose_name='Вопрос-Ответ для основного вида работы')),
                ('subService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.SubServiceName', verbose_name='Вопрос-Ответ для подвида работы')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'Вопросы-Ответы',
            },
        ),
    ]
