# Generated by Django 2.2.6 on 2019-11-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workName', models.CharField(max_length=255, verbose_name='Вид работы')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('about', models.CharField(max_length=255, verbose_name='Тема')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Объем')),
                ('deadLine', models.CharField(blank=True, default='Пользователь не указал', max_length=255, verbose_name='Срок')),
                ('name', models.CharField(default='Нет данных', max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(default='Нет данных', max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(default='Нет данных', max_length=255, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='CallbackOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='Нет данных', max_length=255, verbose_name='Имя')),
                ('userPhone', models.CharField(default='Нет данных', max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Форма заказа звонка',
                'verbose_name_plural': 'Формы заказа звонка',
            },
        ),
        migrations.CreateModel(
            name='CallbackFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='callback_files', verbose_name='Загруженный файл')),
                ('callback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callback.Callback')),
            ],
        ),
    ]
