# Generated by Django 2.2.6 on 2019-11-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackfiles',
            options={'verbose_name': 'Прикрепленный файл к форме', 'verbose_name_plural': 'Прикрепленные файлы к форме'},
        ),
    ]
