# Generated by Django 2.2.6 on 2019-10-27 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workName', models.CharField(max_length=255, verbose_name='Вид работы')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('about', models.CharField(max_length=255, verbose_name='Тема')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Объем')),
                ('deadLine', models.CharField(blank=True, default='Пользователь не указал', max_length=255, verbose_name='Срок')),
                ('file', models.FileField(blank=True, upload_to='new_order_files', verbose_name='Загруженный файл')),
                ('fullPrice', models.IntegerField(default=0, verbose_name='Полная стоимость')),
                ('prePay', models.IntegerField(default=0, verbose_name='Предоплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Заказ выполнен ?')),
                ('complete', models.IntegerField(default=0, verbose_name='Процент готовности (отображается в ЛК)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к заказу от пользователя')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='Комментарий к заказу (виден только админу)')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к файлу (виден пользователю)')),
                ('file', models.FileField(null=True, upload_to='order_files', verbose_name='Файл')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='К заказу')),
            ],
            options={
                'verbose_name': 'Файл к заказу',
                'verbose_name_plural': 'Файлы к заказам',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderStatus', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='Сообщение')),
                ('reply', models.TextField(default='', verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сообщения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Сообщение к заказу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
            ],
            options={
                'verbose_name': 'Сообщение к заказу',
                'verbose_name_plural': 'Сообщения к заказам',
            },
        ),
    ]
