# Generated by Django 2.2.6 on 2019-10-22 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workName', models.CharField(max_length=255, verbose_name='Вид работы')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('about', models.CharField(max_length=255, verbose_name='Тема')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Объем')),
                ('deadLine', models.CharField(blank=True, default='Пользователь не указал', max_length=255, verbose_name='Срок')),
                ('file', models.FileField(blank=True, upload_to='callback_files', verbose_name='Загруженный файл')),
                ('fullPrice', models.IntegerField(default=0, verbose_name='Полная стоимость')),
                ('prePay', models.IntegerField(default=0, verbose_name='Предоплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Заказ выполнен ?')),
                ('complete', models.IntegerField(default=0, verbose_name='Процент готовности (отображается в ЛК)')),
                ('comment', models.TextField(default='', verbose_name='Комментарий к заказу от пользователя')),
                ('admin_comment', models.TextField(default='', verbose_name='Комментарий к заказу (виден только админу)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', verbose_name='Комментарий к файлу (виден пользователю)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='К заказу')),
            ],
            options={
                'verbose_name': 'Файл к заказу',
                'verbose_name_plural': 'Файлы к заказам',
            },
        ),
    ]
