# Generated by Django 2.2.6 on 2019-11-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfile',
            options={'verbose_name': 'Файл выполненной работы', 'verbose_name_plural': 'Выполненные работы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
    ]
